name: Bleeping CVE Automation

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python bleeping.py

      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add data.xlsx
          git commit -m "update CVEs" || echo "no changes"
          git push
